// Code generated by MockGen. DO NOT EDIT.
// Source: webService.go

// Package ch5 is a generated GoMock package.
package ch5

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIWebService is a mock of IWebService interface.
type MockIWebService struct {
	ctrl     *gomock.Controller
	recorder *MockIWebServiceMockRecorder
}

// MockIWebServiceMockRecorder is the mock recorder for MockIWebService.
type MockIWebServiceMockRecorder struct {
	mock *MockIWebService
}

// NewMockIWebService creates a new mock instance.
func NewMockIWebService(ctrl *gomock.Controller) *MockIWebService {
	mock := &MockIWebService{ctrl: ctrl}
	mock.recorder = &MockIWebServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebService) EXPECT() *MockIWebServiceMockRecorder {
	return m.recorder
}

// LogError mocks base method.
func (m *MockIWebService) LogError(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogError", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogError indicates an expected call of LogError.
func (mr *MockIWebServiceMockRecorder) LogError(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockIWebService)(nil).LogError), message)
}
