// Code generated by MockGen. DO NOT EDIT.
// Source: emailService.go

// Package ch5 is a generated GoMock package.
package ch5

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIEmailService is a mock of IEmailService interface.
type MockIEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockIEmailServiceMockRecorder
}

// MockIEmailServiceMockRecorder is the mock recorder for MockIEmailService.
type MockIEmailServiceMockRecorder struct {
	mock *MockIEmailService
}

// NewMockIEmailService creates a new mock instance.
func NewMockIEmailService(ctrl *gomock.Controller) *MockIEmailService {
	mock := &MockIEmailService{ctrl: ctrl}
	mock.recorder = &MockIEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmailService) EXPECT() *MockIEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockIEmailService) SendEmail(to, body, subject string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEmail", to, body, subject)
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockIEmailServiceMockRecorder) SendEmail(to, body, subject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockIEmailService)(nil).SendEmail), to, body, subject)
}
