// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IWebService is an autogenerated mock type for the IWebService type
type IWebService struct {
	mock.Mock
}

// LogError provides a mock function with given fields: message
func (_m *IWebService) LogError(message string) {
	_m.Called(message)
}

type mockConstructorTestingTNewIWebService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIWebService creates a new instance of IWebService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIWebService(t mockConstructorTestingTNewIWebService) *IWebService {
	mock := &IWebService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
